import { Metadata } from "next"
import "./globals.css";

export const metadata : Metadata = {
  title: {
    absolute: "",
    default: "Welcome to File Upload",
    template: "%s | File Upload"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  )
}
